"""This module provides shared constants."""

# Redis
REDIS_API_PREFIX = "API"
REDIS_ROUTES_MIN_SPEED_KEY = f"{REDIS_API_PREFIX}:ROUTES_MIN_SPEED"
REDIS_GTFS_ODOMETERS_KEY_KEY = f"{REDIS_API_PREFIX}:GTFS_ODOMETERS"
